services:
  gasmeter:
    image: gasmeter
    container_name: gasmeter
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ${PWD}/gasmeter.conf:/etc/gasmeter.conf
    devices:
      - /dev/ttyUSB0
    # gasmeter:uucp
    user: 967:986
