{
 "title": "Gasmeter",
 "description": "Show data from a smart energy meter",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Total Gas",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "m3" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  time,\n  volume\nFROM live\nWHERE\n  $__timeFilter(time)\nORDER BY 1;"
    }
   ]
  },
  {
   "title": "Gas Today",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "m3" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  date_trunc('day', NOW()) AS time,\n  (last(volume, time) - first(volume, time)) AS volume\nFROM live\nWHERE\n  time > date_trunc('day', NOW())"
    }
   ]
  },
  {
   "title": "Gas Flow",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT\n  time,\n  state\nFROM live\nWHERE\n  $__timeFilter(time)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Average Bill",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() AS time,\n  avg(bill)\nFROM monthly_view"
    }
   ]
  },
  {
   "title": "Current Bill",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  date_trunc('month', NOW()) AS time,\n  sum(bill) AS bill\nFROM daily_view\nWHERE\n  time > date_trunc('month', NOW())"
    }
   ]
  },
  {
   "title": "Daily Gas",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "m3" } },
   "targets": [
    {
     "rawSql": "SELECT\n  time,\n  volume AS volume\nFROM daily_view\nWHERE\n  $__timeFilter(time)\nORDER BY 1;"
    },
    {
     "rawSql": "SELECT\n  time,\n  bill\nFROM daily_view\nWHERE\n  $__timeFilter(time)\nORDER BY 1;"
    }
   ]
  },
  {
   "title": "Monthly Gas",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "m3" } },
   "targets": [
    {
     "rawSql": "SELECT\n  time,\n  volume\nFROM monthly_view\nWHERE\n  $__timeFilter(time)\nORDER BY time"
    },
    {
     "rawSql": "SELECT\n  time,\n  bill\nFROM monthly_view\nWHERE\n  $__timeFilter(time)\nORDER BY time"
    }
   ]
  }
 ]
}